server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/RGBRenegadeResource
    username: RGBResourceUser
    password: Test123!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/issuer
          jwk-set-uri: http://localhost:8080/auth/.well-known/jwks.json

app:
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080,http://localhost:8081
    maxAgeMs: 3600