server:
  port: 0

spring:
  application:
    name: rgb-image-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: images
      username: rgb
      password: rgb123!1923
      authentication-database: admin
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://rgbIsLit:maarPasswordsZijnLitter@localhost:8761/eureka
