server:
  port: 0

spring:
  application:
    name: rgb-messaging-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://rgbIsLit:maarPasswordsZijnLitter@localhost:8761/eureka

app:
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080,http://localhost:8090,http://10.10.1.40:3000

